# Generated by Django 4.1.3 on 2022-11-19 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 19, 23, 17, 59, 765450, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(default='pending', max_length=1000000)),
            ],
        ),
    ]
